export const createProposalBoard = (proposalId: number) => {
  return {
    nodes: {
      "0ee615e9-b0db-4a62-a580-6461cb828a68": {
        id: "0ee615e9-b0db-4a62-a580-6461cb828a68",
        dom: null,
        data: {
          name: "proposal-roadmap",
          nodes: [],
          props: {
            title: "Proposal Roadmap",
            width: 100,
            colors: ["indigo"],
            height: 100,
            layout: {
              h: 7,
              i: "0ee615e9-b0db-4a62-a580-6461cb828a68",
              w: 24,
              x: 0,
              y: 103,
              moved: false,
              static: false,
            },
            controls: "simple",
            gridSpan: 1,
            background: "transparent",
            fullScreen: false,
            paddingTop: 0,
            proposalId,
            sidePannel: false,
            paddingLeft: 0,
            borderRadius: 0,
            paddingRight: 0,
            paddingBottom: 0,
          },
          hidden: false,
          parent: null,
          displayName: "t",
          linkedNodes: {},
        },
        events: {
          dragged: false,
          hovered: false,
          selected: false,
        },
        related: {},
        _hydrationTimestamp: 1696183838644,
      },
      "1c5dbecf-57ab-4d4c-baf4-8dfa48f46c3e": {
        id: "1c5dbecf-57ab-4d4c-baf4-8dfa48f46c3e",
        dom: null,
        data: {
          name: "Proposal Team",
          nodes: [],
          props: {
            title: "",
            width: 100,
            height: 100,
            layout: {
              h: 18,
              i: "1c5dbecf-57ab-4d4c-baf4-8dfa48f46c3e",
              w: 24,
              x: 0,
              y: 46,
              moved: false,
              static: false,
            },
            controls: "simple",
            gridSpan: 1,
            background: "transparent",
            fullScreen: false,
            paddingTop: 0,
            proposalId,
            sidePannel: false,
            paddingLeft: 0,
            borderRadius: 0,
            paddingRight: 0,
            paddingBottom: 0,
          },
          hidden: false,
          parent: null,
          displayName: "t",
          linkedNodes: {},
        },
        events: {
          dragged: false,
          hovered: false,
          selected: false,
        },
        related: {},
        _hydrationTimestamp: 1696183838645,
      },
      "2afba2e7-50e4-4d67-94bd-aaec3a7dfd5f": {
        id: "2afba2e7-50e4-4d67-94bd-aaec3a7dfd5f",
        dom: null,
        data: {
          name: "proposal-view",
          nodes: [],
          props: {
            title: "",
            width: 100,
            height: 100,
            layout: {
              h: 30,
              i: "2afba2e7-50e4-4d67-94bd-aaec3a7dfd5f",
              w: 24,
              x: 0,
              y: 16,
              moved: false,
              static: false,
            },
            controls: "simple",
            gridSpan: 1,
            background: "transparent",
            fullScreen: false,
            paddingTop: 0,
            proposalId,
            sidePannel: false,
            paddingLeft: 0,
            borderRadius: 0,
            paddingRight: 0,
            paddingBottom: 0,
          },
          hidden: false,
          parent: null,
          displayName: "t",
          linkedNodes: {},
        },
        events: {
          dragged: false,
          hovered: false,
          selected: false,
        },
        related: {},
        _hydrationTimestamp: 1696183838645,
      },
      "498f9c5b-86c3-4a3c-9b4c-ef4a7c2cf13c": {
        id: "498f9c5b-86c3-4a3c-9b4c-ef4a7c2cf13c",
        dom: null,
        data: {
          name: "proposal-4-in-one",
          nodes: [],
          props: {
            title: "",
            width: 100,
            height: 100,
            layout: {
              h: 16,
              i: "498f9c5b-86c3-4a3c-9b4c-ef4a7c2cf13c",
              w: 12,
              x: 0,
              y: 0,
              moved: false,
              static: false,
            },
            controls: "simple",
            gridSpan: 1,
            background: "transparent",
            fullScreen: false,
            paddingTop: 0,
            proposalId,
            sidePannel: false,
            paddingLeft: 0,
            borderRadius: 0,
            paddingRight: 0,
            paddingBottom: 0,
          },
          hidden: false,
          parent: null,
          displayName: "t",
          linkedNodes: {},
        },
        events: {
          dragged: false,
          hovered: false,
          selected: false,
        },
        related: {},
        _hydrationTimestamp: 1696183838645,
      },
      "93910f0e-6bd4-4166-9610-2ddea61c716d": {
        id: "93910f0e-6bd4-4166-9610-2ddea61c716d",
        dom: null,
        data: {
          name: "proposal-kpi",
          nodes: [],
          props: {
            title: "",
            width: 100,
            height: 100,
            layout: {
              h: 16,
              i: "93910f0e-6bd4-4166-9610-2ddea61c716d",
              w: 12,
              x: 12,
              y: 0,
              moved: false,
              static: false,
            },
            controls: "simple",
            gridSpan: 1,
            background: "transparent",
            fullScreen: false,
            paddingTop: 0,
            proposalId,
            sidePannel: false,
            paddingLeft: 0,
            borderRadius: 0,
            paddingRight: 0,
            paddingBottom: 0,
          },
          hidden: false,
          parent: null,
          displayName: "t",
          linkedNodes: {},
        },
        events: {
          dragged: false,
          hovered: false,
          selected: false,
        },
        related: {},
        _hydrationTimestamp: 1696183838645,
      },
      "d4cffdbd-5518-452e-9d63-262ae9cac04e": {
        id: "d4cffdbd-5518-452e-9d63-262ae9cac04e",
        dom: null,
        data: {
          name: "proposal-budget",
          nodes: [],
          props: {
            title: "",
            width: 100,
            colors: ["gray", "gray", "gray", "gray", "gray", "gray", "gray"],
            height: 100,
            layout: {
              h: 16,
              i: "d4cffdbd-5518-452e-9d63-262ae9cac04e",
              w: 23,
              x: 0,
              y: 64,
              moved: false,
              static: false,
            },
            controls: "simple",
            gridSpan: 1,
            background: "transparent",
            fullScreen: false,
            paddingTop: 0,
            proposalId,
            sidePannel: false,
            paddingLeft: 0,
            borderRadius: 0,
            paddingRight: 0,
            paddingBottom: 0,
          },
          hidden: false,
          parent: null,
          displayName: "t",
          linkedNodes: {},
        },
        events: {
          dragged: false,
          hovered: false,
          selected: false,
        },
        related: {},
        _hydrationTimestamp: 1696183838645,
      },
      "d7d29ddc-33ff-4ab5-91d6-e542ea40a5e8": {
        id: "d7d29ddc-33ff-4ab5-91d6-e542ea40a5e8",
        dom: null,
        data: {
          name: "Proposal Votes",
          nodes: [],
          props: {
            title: "Votes",
            width: 100,
            height: 100,
            layout: {
              h: 23,
              i: "d7d29ddc-33ff-4ab5-91d6-e542ea40a5e8",
              w: 24,
              x: 0,
              y: 80,
              moved: false,
              static: false,
            },
            controls: "simple",
            gridSpan: 1,
            background: "transparent",
            fullScreen: false,
            paddingTop: 0,
            proposalId,
            sidePannel: false,
            paddingLeft: 0,
            borderRadius: 0,
            paddingRight: 0,
            paddingBottom: 0,
          },
          hidden: false,
          parent: null,
          displayName: "t",
          linkedNodes: {},
        },
        events: {
          dragged: false,
          hovered: false,
          selected: false,
        },
        related: {},
        _hydrationTimestamp: 1696183838645,
      },
    },
  };
};
