export const createProposalBoard = (proposalId: number) => {
  return {
    nodes: {
      "0ee615e9-b0db-4a62-a580-6461cb828a68": {
        id: "0ee615e9-b0db-4a62-a580-6461cb828a68",
        _hydrationTimestamp: 1696278779759,
        data: {
          props: {
            controls: "simple",
            width: 100,
            height: 100,
            paddingLeft: 0,
            paddingRight: 0,
            paddingTop: 0,
            paddingBottom: 0,
            sidePannel: false,
            fullScreen: false,
            background: "transparent",
            title: "Proposal Roadmap",
            borderRadius: 0,
            gridSpan: 1,
            layout: {
              w: 12,
              h: 11,
              x: 0,
              y: 54,
              i: "0ee615e9-b0db-4a62-a580-6461cb828a68",
              minW: null,
              maxW: null,
              minH: null,
              maxH: null,
              moved: false,
              static: false,
              isDraggable: null,
              isResizable: null,
              resizeHandles: null,
              isBounded: null,
            },
            colors: ["indigo"],
            proposalId,
          },
          parent: null,
          hidden: false,
          nodes: [],
          linkedNodes: {},
          name: "proposal-roadmap",
          displayName: "t",
        },
        related: {},
        events: {
          selected: false,
          dragged: false,
          hovered: false,
        },
        dom: null,
      },
      "1c5dbecf-57ab-4d4c-baf4-8dfa48f46c3e": {
        id: "1c5dbecf-57ab-4d4c-baf4-8dfa48f46c3e",
        _hydrationTimestamp: 1696278779759,
        data: {
          props: {
            controls: "simple",
            width: 100,
            height: 100,
            paddingLeft: 0,
            paddingRight: 0,
            paddingTop: 0,
            paddingBottom: 0,
            sidePannel: false,
            fullScreen: false,
            background: "transparent",
            title: "",
            borderRadius: 0,
            gridSpan: 1,
            layout: {
              w: 12,
              h: 9,
              x: 0,
              y: 65,
              i: "1c5dbecf-57ab-4d4c-baf4-8dfa48f46c3e",
              minW: null,
              maxW: null,
              minH: null,
              maxH: null,
              moved: false,
              static: false,
              isDraggable: null,
              isResizable: null,
              resizeHandles: null,
              isBounded: null,
            },
            proposalId,
          },
          parent: null,
          hidden: false,
          nodes: [],
          linkedNodes: {},
          name: "Proposal Team",
          displayName: "t",
        },
        related: {},
        events: {
          selected: false,
          dragged: false,
          hovered: false,
        },
        dom: null,
      },
      "2afba2e7-50e4-4d67-94bd-aaec3a7dfd5f": {
        id: "2afba2e7-50e4-4d67-94bd-aaec3a7dfd5f",
        _hydrationTimestamp: 1696278779759,
        data: {
          props: {
            controls: "simple",
            width: 100,
            height: 100,
            paddingLeft: 0,
            paddingRight: 0,
            paddingTop: 0,
            paddingBottom: 0,
            sidePannel: false,
            fullScreen: false,
            background: "transparent",
            title: "",
            borderRadius: 0,
            gridSpan: 1,
            layout: {
              w: 24,
              h: 16,
              x: 0,
              y: 0,
              i: "2afba2e7-50e4-4d67-94bd-aaec3a7dfd5f",
              minW: null,
              maxW: null,
              minH: null,
              maxH: null,
              moved: false,
              static: false,
              isDraggable: null,
              isResizable: null,
              resizeHandles: null,
              isBounded: null,
            },
            proposalId,
          },
          parent: null,
          hidden: false,
          nodes: [],
          linkedNodes: {},
          name: "proposal-view",
          displayName: "t",
        },
        related: {},
        events: {
          selected: true,
          dragged: false,
          hovered: false,
        },
        dom: null,
      },
      "498f9c5b-86c3-4a3c-9b4c-ef4a7c2cf13c": {
        id: "498f9c5b-86c3-4a3c-9b4c-ef4a7c2cf13c",
        _hydrationTimestamp: 1696278779759,
        data: {
          props: {
            controls: "simple",
            width: 100,
            height: 100,
            paddingLeft: 0,
            paddingRight: 0,
            paddingTop: 0,
            paddingBottom: 0,
            sidePannel: false,
            fullScreen: false,
            background: "transparent",
            title: "",
            borderRadius: 0,
            gridSpan: 1,
            layout: {
              w: 24,
              h: 9,
              x: 0,
              y: 16,
              i: "498f9c5b-86c3-4a3c-9b4c-ef4a7c2cf13c",
              minW: null,
              maxW: null,
              minH: null,
              maxH: null,
              moved: false,
              static: false,
              isDraggable: null,
              isResizable: null,
              resizeHandles: null,
              isBounded: null,
            },
            proposalId,
          },
          parent: null,
          hidden: false,
          nodes: [],
          linkedNodes: {},
          name: "proposal-4-in-one",
          displayName: "t",
        },
        related: {},
        events: {
          selected: false,
          dragged: false,
          hovered: false,
        },
        dom: null,
      },
      "93910f0e-6bd4-4166-9610-2ddea61c716d": {
        id: "93910f0e-6bd4-4166-9610-2ddea61c716d",
        _hydrationTimestamp: 1696278779759,
        data: {
          props: {
            controls: "simple",
            width: 100,
            height: 100,
            paddingLeft: 0,
            paddingRight: 0,
            paddingTop: 0,
            paddingBottom: 0,
            sidePannel: false,
            fullScreen: false,
            background: "transparent",
            title: "Votes Overview",
            borderRadius: 0,
            gridSpan: 1,
            layout: {
              w: 7,
              h: 29,
              x: 0,
              y: 25,
              i: "93910f0e-6bd4-4166-9610-2ddea61c716d",
              minW: null,
              maxW: null,
              minH: null,
              maxH: null,
              moved: false,
              static: false,
              isDraggable: null,
              isResizable: null,
              resizeHandles: null,
              isBounded: null,
            },
            proposalId,
          },
          parent: null,
          hidden: false,
          nodes: [],
          linkedNodes: {},
          name: "proposal-kpi",
          displayName: "t",
        },
        related: {},
        events: {
          selected: false,
          dragged: false,
          hovered: false,
        },
        dom: null,
      },
      "d4cffdbd-5518-452e-9d63-262ae9cac04e": {
        id: "d4cffdbd-5518-452e-9d63-262ae9cac04e",
        _hydrationTimestamp: 1696278779759,
        data: {
          props: {
            controls: "simple",
            width: 100,
            height: 100,
            paddingLeft: 0,
            paddingRight: 0,
            paddingTop: 0,
            paddingBottom: 0,
            sidePannel: false,
            fullScreen: false,
            background: "transparent",
            title: "",
            borderRadius: 0,
            gridSpan: 1,
            layout: {
              w: 12,
              h: 16,
              x: 0,
              y: 74,
              i: "d4cffdbd-5518-452e-9d63-262ae9cac04e",
              minW: null,
              maxW: null,
              minH: null,
              maxH: null,
              moved: false,
              static: false,
              isDraggable: null,
              isResizable: null,
              resizeHandles: null,
              isBounded: null,
            },
            colors: ["gray", "gray"],
            proposalId,
          },
          parent: null,
          hidden: false,
          nodes: [],
          linkedNodes: {},
          name: "proposal-budget",
          displayName: "t",
        },
        related: {},
        events: {
          selected: false,
          dragged: false,
          hovered: false,
        },
        dom: null,
      },
      "d7d29ddc-33ff-4ab5-91d6-e542ea40a5e8": {
        id: "d7d29ddc-33ff-4ab5-91d6-e542ea40a5e8",
        _hydrationTimestamp: 1696278779759,
        data: {
          props: {
            controls: "simple",
            width: 100,
            height: 100,
            paddingLeft: 0,
            paddingRight: 0,
            paddingTop: 0,
            paddingBottom: 0,
            sidePannel: false,
            fullScreen: false,
            background: "transparent",
            title: "Votes (46)",
            borderRadius: 0,
            gridSpan: 1,
            layout: {
              w: 17,
              h: 29,
              x: 7,
              y: 25,
              i: "d7d29ddc-33ff-4ab5-91d6-e542ea40a5e8",
              minW: null,
              maxW: null,
              minH: null,
              maxH: null,
              moved: false,
              static: false,
              isDraggable: null,
              isResizable: null,
              resizeHandles: null,
              isBounded: null,
            },
            proposalId,
          },
          parent: null,
          hidden: false,
          nodes: [],
          linkedNodes: {},
          name: "Proposal Votes",
          displayName: "t",
        },
        related: {},
        events: {
          selected: false,
          dragged: false,
          hovered: false,
        },
        dom: null,
      },
    },
  };
};
